repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        files: ^pmps/
        args: [--diff]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        verbose: true
        files: ^pmps/
        entry: bash -c 'mypy "$@" || true' --

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a3
  hooks:
    - id: pylint
      args:
        [ "pmps/",
          "--fail-under=6"
        ]
