name: tests-code

on:
  push:
    branches: [main, pytest]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, review_requested, ready_for_review]
#  schedule:
#    - cron: "0 4 * * *"

jobs:
  tests-cpu:
    name: "unit test the package"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.9, 3.10 ]
        include:
          - env: "test"
            prefix: /usr/share/miniconda3/envs/docs
            pip_path: ~/.cache/pip
    steps:
    - uses: actions/checkout@v2
    - name: check packaging file
      run: cat ${{ format('packaging/{0}_env.yml', matrix.packaging) }}
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: ${{ matrix.packaging }}
        use-mamba: true
        python-version: ${{ matrix.python-version }}

    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - uses: actions/cache@v2
      with:
        path: ${{ matrix.prefix }}
        key: ${{ matrix.label }}-conda-${{ hashFiles(format('packaging/{0}_env.yml', matrix.packaging)) }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      id: cache

    - name: Update environment
      run: mamba packaging update -n docs -f ${{ format('packaging/{0}_env.yml', matrix.packaging) }}
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info -a
        conda list
    - name: Run Tests
      shell: bash -l {0}
      run: pytest -v --cov=pmps.api --cov-report xml test/ --flake8 --mypy
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        flags: pytest, os${{ matrix.os }}, python${{ matrix.python-version }}
        name: coverage-pmps
